### ISSUE TITLE
test: dask Backend specific xfailed tests

### ISSUE THREAD

**Issue by gerrymanoim** [ibis-project/ibis#2553]
This tracks tests xfailed **only** in the dask backend (i.e. not the pandas backend). This provides a good tracker of compatibility differences. In the codebase sections of not working code will be marked `TODO - <reason keyword> - #2553`. 

# Backend Specific Tests

| Done? | test file | test name | reason | keyword |GH Issue |
| ------- | --------- | --------- | ------ | ------- | ------- |
| :x: | test_datatypes | test_series_to_ibis_literal | `ir.as_value_expr` does not handle `dd.Series` | as_value_expr | |
| :x: | test_arrays | test_array_collect_rolling_partitioned | Windowing not implemented | windowing | |
| :x: | test_join | test_join_with_non_trivial_key | `execute_materialized_join` is broken | execute_materialized_join | |
| :x: | test_join | test_join_with_non_trivial_key_project_table | `execute_materialized_join` is broken | execute_materialized_join | |
| :x: | test_operations | test_project_scope_does_not_override | Windowing not implemented | windowing | |
| :heavy_check_mark: | test_operations | test_aggregation_group_by | Aggregations not implemented | aggregations | |
| :heavy_check_mark: | test_operations | test_boolean_aggregation | Aggregations not implemented | aggregations | |
| :x: | test_operations | test_sort_by | Sorting partially implemented | sorting | |
| :x: | test_operations | test_complex_sort_by | Sorting partially implemented | sorting | |
| :heavy_check_mark: | test_operations | test_weighted_average | Grouping not implemented | grouping | |
| :heavy_check_mark: | test_operations | test_groupby_with_unnamed_arithmetic | Grouping not implemented | grouping | |
| :heavy_check_mark: | test_operations | test_cast_on_group_by | Grouping not implemented | grouping | |
| :heavy_check_mark: | test_operations | test_left_binary_op_gb | Aggregations not implemented | aggregations | |
| :heavy_check_mark: | test_structs | test_struct_field_series_group_by_value | Grouping not implemented | grouping | |
| :x: | test_timecontext | test_context_adjustment_window | Windowing not implemented | windowing | |
| :x: | test_timecontext | test_setting_timecontext_in_scope | Windowing not implemented | windowing | |
| :x: | test_timecontext | test_context_adjustment_multi_window | Windowing not implemented | windowing | |
| :x: | test_timecontext | test_context_adjustment_window_groupby_id | Windowing not implemented | windowing | |
| :x: | test_udf | test_udaf_analytic_groupby | Windowing not implemented | windowing | |
| :x: | test_udf | test_udaf_window | Windowing not implemented | windowing | |
| :x: | test_udf | test_udaf_window_interval | Windowing not implemented | windowing | |
| :x: | test_udf | test_multiple_argument_udaf_window | Windowing not implemented | windowing | |
| :x: | test_udf | test_udaf_window_nan | Windowing not implemented | windowing | |
| ✔️  | test_udf | test_array_return_type_reduction_window | Windowing not implemented | windowing | |

# Ibis/all tests

| Done? | test file | test name | reason | keyword |GH Issue |
| ----- | --------- | --------- | ------ | ------- | ------- |
| :heavy_check_mark: | test_join| test_join_project_left_table| Pandas used in test | pandas| |
| :heavy_check_mark: | test_generic | test_isin | Sorting not implemented | sorting | |
| :heavy_check_mark: | test_generic | test_notin | Sorting not implemented | sorting | |
| :heavy_check_mark: | test_union | test_union | Pandas used in test | pandas| |
| :heavy_check_mark: | test_aggregations | test_aggregate | Aggregations not implemented / pandas in test | aggregations | |
| :heavy_check_mark: | test_aggregations | test_aggregate_grouped | Aggregations not implemented / pandas in test | aggregations | |
| :heavy_check_mark: | test_aggregations | test_reduction_ops | iloc used in test | iloc | |
| :heavy_check_mark: | test_aggregations | test_group_concat | Aggregations not implemented / iloc in test | aggregations | |
| :heavy_check_mark: | test_aggregations | test_topk_op | Sorting not implemented / pandas in test | sorting | |
| :heavy_check_mark: | test_aggregations | test_topk_filter_op | Sorting not implemented / pandas in test | sorting | |
| :heavy_check_mark: | test_string | test_string_col_is_unicode | pandas used in test body | pandas | |
| :x: | test_string | test_string | different dtypes returned | dtype | |
| :x: | test_string | test_string | Substring operations not implemented | substring | |
| :heavy_check_mark: | test_temporal | test_timestamp_truncate | pandas used in test body | pandas | |
| :heavy_check_mark: | test_temporal | test_date_truncate | pandas used in test body | pandas | |
| :x: | test_temporal | test_integer_to_interval_timestamp | Dask issues with DateOffset | DateOffset | https://github.com/dask/dask/issues/6958 |
| :x: | test_temporal | test_integer_to_interval_date | Dask issues with DateOffset | DateOffset | https://github.com/dask/dask/issues/6958 |
| :heavy_check_mark: | test_temporal | test_temporal_binop | pandas used in test body | pandas | |
| :heavy_check_mark: | test_temporal | test_interval_add_cast_column | pandas used in test body (sorting) | pandas | |
| :heavy_check_mark: | test_temporal | test_day_of_week_column_group_by | pandas used in test body (sorting) | pandas| |
| :x: | test_temporal | test_now_from_projection | limit does not work | limit | |
| ✔️ : | test_vectorized_udf | test_analytic_udf_mutate | Windowing not implemented | windowing| |
| :x: | test_vectorized_udf | test_analytic_udf_destruct| Windowing not implemented | windowing| |
| :x: | test_vectorized_udf | test_analytic_udf_destruct_overwrite | Windowing not implemented | windowing| |
| :x: | test_vectorized_udf | test_reduction_udf_destruct_window | Windowing not implemented | windowing| |

## Notes

- Many of the aggregation/grouping issues are interrelated (we often group before performing an aggregation)
- AggContext has also not been implemented for the dask backend. 
- A large portion of the grouping issues are due to the fact that `obj` and `grouper` methods on Dask `GroupBy` structures

**Comment by jreback** [comment]
you can add checkboxes to the above table to make this easier once these are starting to get fixed

**Comment by emilyreff7** [comment]
A few additional tests were newly x-failed in the dask backend in this PR https://github.com/ibis-project/ibis/pull/2776/:

| test file | test name | reason |
| -------  | ---------  | ------- |
| test_vectorized_udf.py | test_elementwise_udf_destruct             | Length mismatch |
| test_vectorized_udf.py | test_elementwise_udf_overwrite_destruct             | Length mismatch |
| test_vectorized_udf.py | test_elementwise_udf_overwrite_destruct_and_assign             | Length mismatch |
| test_vectorized_udf.py | test_elementwise_udf_destruct_exact_once             | Length mismatch |
| test_vectorized_udf.py | test_elementwise_udf_multiple_overwrite_destruct             | Length mismatch |

**Comment by timothydijamco** [comment]
Xfailed tests from #2753:

| test file        | test name    | reason         |
| ------------- | ------------- |------------- |
| test_arrays.py | test_array_slice | Need an `ops.ArraySlice` execution func that dispatches on `dd.Series` |
| test_arrays.py | test_array_repeat | Need an `ops.ArrayRepeat` execution func that dispatches on `dd.Series` |
| test_arrays.py | test_array_concat | Need an `ops.ArrayConcat` execution func that dispatches on `dd.Series` |
| test_functions.py | test_quantile_list | Need an `ops.MultiQuantile` execution func that dispatches on `ndarrays` |
| test_functions.py | test_quantile_array_access | Need an `ops.MultiQuantile` execution func that dispatches on `ndarrays` |
| test_strings.py | test_string_ops (one parameter only) | Need `ops.StringSplit` exec func that dispatches on `dd.Series` |

**Comment by gerrymanoim** [comment]
> A few additional tests were newly x-failed in the dask backend in this PR #2776:
> 
> test file	test name	reason
> test_vectorized_udf.py	test_elementwise_udf_destruct	Length mismatch
> test_vectorized_udf.py	test_elementwise_udf_overwrite_destruct	Length mismatch
> test_vectorized_udf.py	test_elementwise_udf_overwrite_destruct_and_assign	Length mismatch
> test_vectorized_udf.py	test_elementwise_udf_destruct_exact_once	Length mismatch
> test_vectorized_udf.py	test_elementwise_udf_multiple_overwrite_destruct	Length mismatch

These were fixed in https://github.com/ibis-project/ibis/pull/2797/files

**Comment by cpcloud** [comment]
Thanks for the great issue report. Please open specific issues for anything that's still broken. We've done a bunch of clean up work to address the things in this issue.

**Comment by gerrymanoim** [comment]
I think the things marked as broken are still broken? This was just a general tracking issue.
