### ISSUE TITLE
bug: Duckdb backend doesn't handle nested types

### ISSUE THREAD

**Issue by goodwanghan** [ibis-project/ibis#4509]
Here is the code to reproduce the issue:

```python
import duckdb
import pandas as pd
import pyarrow as pa
import ibis

conn = ibis.duckdb.connect()

my_df = pd.DataFrame.from_dict({'a': [[0]], "b": [{"a":1}]})
conn.con.execute("register", ("df", pa.Table.from_pandas(my_df)))
conn.table("df").schema()
```

It will throw an exception. I took a deeper look into the code, and it seems types like `BIGINT[]` can't be correctly parsed by
https://github.com/ibis-project/ibis/blob/898f00276606f43b5c95bd8469230e07b03d759b/ibis/backends/duckdb/datatypes.py#L52

**Comment by goodwanghan** [comment]
Notice the nested types can be more complicated than an array. There can be struct inside struct.

Here is how Fugue (partially) solves this (duckdb type -> pyarrow type):

https://github.com/fugue-project/fugue/blob/e9a706284ec205df351081bf50d51e3d088290cf/fugue_duckdb/_utils.py#L98

**Comment by cpcloud** [comment]
@goodwanghan Thanks for the issue!

It looks like you may be on an older version of ibis, since this is fixed in `master`:

```
In [1]: import duckdb

In [2]: import pandas as pd


In [3]: import pyarrow as pa

In [4]: import ibis

In [5]:

In [5]: conn = ibis.duckdb.connect()

In [6]: my_df = pd.DataFrame.from_dict({'a': [[0]], "b": [{"a":1}]})

In [7]: conn.con.execute("register", ("df", pa.Table.from_pandas(my_df)))
Out[7]: <sqlalchemy.engine.cursor.LegacyCursorResult at 0x7f489e6ace80>

In [8]: conn.table("df").schema()
/nix/store/qmj8ypjlirv761kvr5vw0zs5w8nk89f2-python3-3.10.6-env/lib/python3.10/site-packages/duckdb_engine/__init__.py:229: DuckDBEngineWarning: duckdb-engine doesn't yet support reflection on indices
  warnings.warn(
Out[8]:
ibis.Schema {
  a  array<int64>
  b  struct<a: int64>
}
```

Please reopen if this is still an issue with 3.2.0, which was release yesterday!

**Comment by cpcloud** [comment]
Looks like this was fixed in 3.1.0 in e20bcc094.

Our type parser is pretty comprehensive and should be able to handle all of duckdb's types. If it can't, that's a bug.

**Comment by goodwanghan** [comment]
I checked 3.10 and 3.20 the issue is still there:

![image](https://user-images.githubusercontent.com/21092479/190683297-d6cf9d8c-e227-4802-8657-07bed431d099.png)

**Comment by goodwanghan** [comment]
I also tried the master branch, the issue has not been resolved. That is very weird, how did you install ibis-framework?

**Comment by cpcloud** [comment]
You need to update your version of `duckdb-engine` most likely. See [here](https://ibis-project.org/docs/3.2.0/backends/DuckDB/).

**Comment by cpcloud** [comment]
You may also need to update your version of `duckdb`.

**Comment by cpcloud** [comment]
The bug you're seeing is from a [bug in duckdb 0.4.0 that I fixed upstream](https://github.com/duckdb/duckdb/pull/3953), but that bug fix is only available in 0.5.0. If you install 0.5.0, you have to update your version of `duckdb-engine` to at least 0.6.2.

**Comment by goodwanghan** [comment]
ah! Yes, duckdb 5.0 is working, I also just found out!

**Comment by goodwanghan** [comment]
Sounds great, thank you so much!

**Comment by goodwanghan** [comment]
So it seems the map type is still having issues:

```python
import duckdb
import pandas as pd
import pyarrow as pa
import ibis

conn = ibis.duckdb.connect()

my_df = pd.DataFrame([[[("a",1),("b",2)]]], columns=["a"])
adf = pa.Table.from_pandas(my_df, pa.schema([("a",pa.map_(pa.string(),pa.int32()))]))
print(adf.schema)
conn.con.execute("register", ("df", adf))
conn.table("df").schema()
```

```
File /usr/local/lib/python3.8/site-packages/ibis/backends/duckdb/datatypes.py:158, in parse(text, default_decimal_parameters)
    156 non_pg_array_type = primitive | decimal | list_array | map | struct
    157 ty = pg_array | non_pg_array_type
--> 158 return ty.parse(text)

File /usr/local/lib/python3.8/site-packages/parsy/__init__.py:90, in Parser.parse(self, stream)
     88 def parse(self, stream):
     89     """Parse a string or list of tokens and return the result or raise a ParseError."""
---> 90     (result, _) = (self << eof).parse_partial(stream)
     91     return result

File /usr/local/lib/python3.8/site-packages/parsy/__init__.py:104, in Parser.parse_partial(self, stream)
    102     return (result.value, stream[result.index:])
    103 else:
--> 104     raise ParseError(result.expected, stream, result.furthest)

ParseError: expected '<' at 0:3
```

**Comment by cpcloud** [comment]
Maps in duckdb aren't yet supported because they are multimaps and no one has asked to support them, but we can certainly add the types so you can at least read the thing.

**Comment by goodwanghan** [comment]
Haha, exactly. Thank you! This is not high priority because the use case is not common.
