### ISSUE TITLE
bug: Unable to create temporary table on bigquery

### ISSUE THREAD

**Issue by albertjstanley** [ibis-project/ibis#8975]
### What happened?

I was trying to make a temporary table on bigquery with this code:
```python
import ibis
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    './service_account.json')
con = ibis.bigquery.connect(
    project_id = "ajskdfce-demo",
    dataset_id = "dataset",
    credentials = credentials
)

temp_df = con.table("some_table_id")
temp_table = con.create_table("temp_table_name", temp_df, temp=True)
```

This causes an error (logs below). It works fine if I set temp=False.

### What version of ibis are you using?

8.0.0

### What backend(s) are you using, if any?

BigQuery

### Relevant log output

```sh
Traceback (most recent call last):
  File "/Users/albertstanley/Code/ibis/create_temp_table.py", line 14, in <module>
    temp_table = con.create_table("temp_table_name", temp_df, database="dataset", temp=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ibis/backends/bigquery/__init__.py", line 955, in create_table
    dataset = self._session_dataset.dataset_id
AttributeError: 'NoneType' object has no attribute 'dataset_id'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cpcloud** [comment]
Can you try with a pre-release?

```
pip install 'ibis-framework[bigquery]' --pre --upgrade
```

I believe we've already fixed this.

**Comment by albertjstanley** [comment]
Looks like I'm still getting the error with the pre-release ('9.0.0.dev619').

**Comment by cpcloud** [comment]
Yep, thanks for the report. I am able to reproduce this. PR incoming.
